apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- hoge.yaml
- fuga.yaml
patchesJson6902:
- target:
    group: batch
    version: v1
    kind: Job
    name: fugafuga
  path: patches/genname.yaml
- target:
    group: batch
    version: v1
    kind: Job
    name: hogehoge
  path: patches/genname.yaml
